# Generated by Django 4.2 on 2025-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='implementation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='implementation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved for Implementation'), ('in_progress', 'Implementation in Progress'), ('completed', 'Implementation Completed'), ('rejected', 'Not Feasible')], default='pending', max_length=20),
        ),
    ]
